id = "cooklang"
name = "Cooklang"
version = "1.3.0"                                        # x-release-please-version
schema_version = 1
authors = ["Kyle Huggins <kyle@huggins.io>"]
description = "Cooklang support."
repository = "https://github.com/hugginsio/zed-cooklang"

[grammars.cooklang]
repository = "https://github.com/addcninblue/tree-sitter-cooklang"
commit = "4ebe237c1cf64cf3826fc249e9ec0988fe07e58e"
