# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
on:
  push:
    branches:
      - main

jobs:
  combined-release:
    runs-on: ubuntu-latest
    if: "${{ startsWith(github.ref, 'refs/heads') }}"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: "googleapis/release-please-action@v4"
        id: "release-please"
        name: "Release, Please!"
        with:
          config-file: ".github/release-please/config.json"
          manifest-file: ".github/release-please/manifest.json"
      - uses: huacnlee/zed-extension-action@v1
        name: "Release to Zed"
        if: "${{ startsWith(github.event.head_commit.message, 'chore(main): release ') && startsWith(github.event.head_commit.committer.name, 'GitHub') }}"
        with:
          extension-name: cooklang
          push-to: "hugginsio/zed-extensions"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
