# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    name: "Release, Please!"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: "googleapis/release-please-action@v4"
        id: "release-please"
        with:
          config-file: ".github/release-please/config.json"
          manifest-file: ".github/release-please/manifest.json"
          token: "${{ secrets.COMMITTER_TOKEN }}"
