# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  tag:
    name: "Release, Please!"
    runs-on: ubuntu-latest
    if: "${{ startsWith(github.ref, 'refs/heads') }}"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: "googleapis/release-please-action@v4"
        id: "release-please"
        with:
          config-file: ".github/release-please/config.json"
          manifest-file: ".github/release-please/manifest.json"
  zed:
    name: "Release to Zed"
    runs-on: ubuntu-latest
    if: "${{ steps.release-please.outputs.release }}"
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: cooklang
          push-to: "hugginsio/zed-extensions"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
