# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release to Zed
on:
  push:
    tags:
      - "v*"

jobs:
  zed-extensions-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: cooklang
          push-to: "hugginsio/zed-extensions"
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
